language: python
sudo: false

python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7

install:
  - python3 setup.py build install
  - pip install python-coveralls

script:
  python3 setup.py lint test

after_success:
  coveralls
