#!/usr/bin/env python
# coding: utf8

import argparse
import pycaching
import time

def parse():
    parser = argparse.ArgumentParser(usage="save-gpx -u user -p pass GC12345", description="Retrieve and save information about a cache in GPX format.", add_help=True)
    parser.add_argument("-u", "--user", type=str, dest='user')
    parser.add_argument("-p", "--password", type=str, dest="password")
    parser.add_argument("geocache", nargs='+')
    return parser.parse_args()


def process(opts):
    geocaching = pycaching.login(opts.user, opts.password)
    for cache_name in opts.geocache:
        print("Retrieve %s" % cache_name)
        cache = geocaching.load_cache(cache_name)
        with open(cache_name + ".gpx", "w") as f:
            f.write('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n')
            f.write('<gpx \n')
            f.write('    version="1.0"\n')
            f.write('    creator="pycaching"\n')
            f.write('    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n')
            f.write('    xmlns="http://www.topografix.com/GPX/1/0"\n')
            f.write('    xsi:schemaLocation="http://www.topografix.com/GPX/1/0 http://www.topografix.com/GPX/1/0/gpx.xsd http://www.groundspeak.com/cache/1/0/2 http://www.groundspeak.com/cache/1/0/2/cache.xsd">\n')
            f.write('    <name>GeoCaching GPX</name>\n')
            f.write('    <time>%s</time>\n'%time.strftime("%Y-%m-%dT%H:%M:%S.000Z"))
            f.write('    <keywords>geocache, cache, opencaching, waypoint</keywords>\n')
            f.write(cache.to_gpx())
            f.write('</gpx>')

if __name__=="__main__":
    opts = parse()
    process(opts)
